// <auto-generated />
using EcomProject_JimmyRebecca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcomProject_JimmyRebecca.Migrations.ProductDB
{
    [DbContext(typeof(ProductDBContext))]
    partial class ProductDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EcomProject_JimmyRebecca.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.Property<decimal>("SuggestedDonation");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new { ID = 1, Description = "It's garfield, who doesn't want garfield???", ProductName = "Tabby", SuggestedDonation = 900m },
                        new { ID = 2, Description = "Endless fun! For your cat too, I guess...", ProductName = "Laser Pointer", SuggestedDonation = 30m },
                        new { ID = 3, Description = "When you just don't wanna deal with them anymore", ProductName = "Catnip", SuggestedDonation = 35m },
                        new { ID = 4, Description = "Scottish folds are normal cats that fold their ears.", ProductName = "Scottish Fold", SuggestedDonation = 1100m },
                        new { ID = 5, Description = "They might not like it, but it'll keep them warm", ProductName = "Cat-shirt", SuggestedDonation = 40m },
                        new { ID = 6, Description = "This is where lion king started", ProductName = "Cat Post", SuggestedDonation = 75m },
                        new { ID = 7, Description = "It's like a bengal, but less dangerous.", ProductName = "Bengal", SuggestedDonation = 900m },
                        new { ID = 8, Description = "Buy a cat a home, they'll leave you forever.", ProductName = "Cat-stle", SuggestedDonation = 120m },
                        new { ID = 9, Description = "When you want mindless zombies...", ProductName = "Cat Food", SuggestedDonation = 50m },
                        new { ID = 10, Description = "If you enjoy vodka, this is your friend.", ProductName = "Russian Blue", SuggestedDonation = 900m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
